// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './analytics.runtime.js';
import type * as Contract from './analytics-contracts.js';

export type * from './analytics-contracts.js';

/** Optional framework-neutral current-match history. No timers, transport or persistence. */
export const createMatchHistory: typeof Contract.createMatchHistory = runtime.createMatchHistory;
