// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './app.runtime.js';
import type * as Contract from './app-contracts.js';

export type * from './app-contracts.js';

export const defineApplication: typeof Contract.defineApplication = runtime.defineApplication;
