// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './assets.runtime.js';
import type * as Contract from './assets-contracts.js';

export type * from './assets-contracts.js';

export const assetBaseUrl: typeof Contract.assetBaseUrl = runtime.assetBaseUrl;
export const countryFlagCatalogVersion: typeof Contract.countryFlagCatalogVersion = runtime.countryFlagCatalogVersion;
export const resolveAssetBaseUrl: typeof Contract.resolveAssetBaseUrl = runtime.resolveAssetBaseUrl;
export const normalizeAssetBaseUrl: typeof Contract.normalizeAssetBaseUrl = runtime.normalizeAssetBaseUrl;
export const countryFlagFileName: typeof Contract.countryFlagFileName = runtime.countryFlagFileName;
export const countryFlagUrl: typeof Contract.countryFlagUrl = runtime.countryFlagUrl;
export const countryFlagManifestUrl: typeof Contract.countryFlagManifestUrl = runtime.countryFlagManifestUrl;
