// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './game-data.runtime.js';
import type * as Contract from './game-data-contracts.js';

export type * from './game-data-contracts.js';

/** Loads only the exact revision advertised by the recorder; never substitutes the latest build. */
export const loadGameData: typeof Contract.loadGameData = runtime.loadGameData;
/** A standard-game estimate derived from this revision's ability configuration and observed game time. */
export const abilityCooldown: typeof Contract.abilityCooldown = runtime.abilityCooldown;
export const abilityCooldownsForState: typeof Contract.abilityCooldownsForState = runtime.abilityCooldownsForState;
