// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './index.runtime.js';
import type * as Contract from './contracts.js';

export type * from './contracts.js';
export { SDK_VERSION, PROTOCOL_VERSION, SUPPORTED_PROTOCOL_VERSIONS } from './version.js';

export type PermissionRequiredError = Contract.PermissionRequiredError;
export type ConnectionError = Contract.ConnectionError;
export type ProtocolError = Contract.ProtocolError;
export type HostActionError = Contract.HostActionError;
export type W3BoosterClient<TSettings extends object = Contract.JsonObject, TOverlayExtensions extends object = object> = Contract.W3BoosterClient<TSettings, TOverlayExtensions>;

/** Runtime error constructors exposed for `instanceof` and explicit error creation. */
export const PermissionRequiredError: typeof Contract.PermissionRequiredError = runtime.PermissionRequiredError;
export const ConnectionError: typeof Contract.ConnectionError = runtime.ConnectionError;
export const ProtocolError: typeof Contract.ProtocolError = runtime.ProtocolError;
export const HostActionError: typeof Contract.HostActionError = runtime.HostActionError;
/** Runtime class identity for `instanceof`; clients are created through the factory functions. */
export const W3BoosterClient: typeof Contract.W3BoosterClient = runtime.W3BoosterClient;
/** Open a W3Booster transport without waiting for hydrated state. */
export const openClient: typeof Contract.openClient = runtime.openClient;
/** @deprecated Use openClient() for transport-only startup or startClient() for synchronized state. */
export const connect: typeof Contract.connect = runtime.connect;
/** Create a client and wait for the frontend lifecycle milestone requested by startup options. */
export const startClient: typeof Contract.startClient = runtime.startClient;
/** Create a client synchronously so lifecycle listeners can be attached before connecting. */
export const createClient: typeof Contract.createClient = runtime.createClient;
export const isAbortError: typeof Contract.isAbortError = runtime.isAbortError;
export const isW3BoosterError: typeof Contract.isW3BoosterError = runtime.isW3BoosterError;
export const classifyW3BoosterError: typeof Contract.classifyW3BoosterError = runtime.classifyW3BoosterError;
export const canUseHostCapability: typeof Contract.canUseHostCapability = runtime.canUseHostCapability;
export const UNAVAILABLE_HOST_SNAPSHOT: typeof Contract.UNAVAILABLE_HOST_SNAPSHOT = runtime.UNAVAILABLE_HOST_SNAPSHOT;
