// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './overlay-input.runtime.js';
import type * as Contract from './overlay-input-contracts.js';

export type * from './overlay-input-contracts.js';

/** Enable declarative .w3-interactive regions in an embedded in-game overlay.
 * Initialize once before installing application pointer handlers. In standalone
 * pages and OBS this remains inactive until an in-game compositor handshake.
 */
export const initializeOverlayInput: typeof Contract.initializeOverlayInput = runtime.initializeOverlayInput;
