// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './selectors.runtime.js';
import type * as Contract from './selectors-contracts.js';

export type * from './selectors-contracts.js';

export const isActiveMatch: typeof Contract.isActiveMatch = runtime.isActiveMatch;
export const isObserverOrReplayMatch: typeof Contract.isObserverOrReplayMatch = runtime.isObserverOrReplayMatch;
export const hasCapability: typeof Contract.hasCapability = runtime.hasCapability;
export const broadcasterPlayer: typeof Contract.broadcasterPlayer = runtime.broadcasterPlayer;
export const headToHeadPair: typeof Contract.headToHeadPair = runtime.headToHeadPair;
export const groupPlayersByTeam: typeof Contract.groupPlayersByTeam = runtime.groupPlayersByTeam;
export const broadcasterFirstTeams: typeof Contract.broadcasterFirstTeams = runtime.broadcasterFirstTeams;
export const playerRelationship: typeof Contract.playerRelationship = runtime.playerRelationship;
export const playerDisplayIdentity: typeof Contract.playerDisplayIdentity = runtime.playerDisplayIdentity;
export const heroInventory: typeof Contract.heroInventory = runtime.heroInventory;
export const playerHeroes: typeof Contract.playerHeroes = runtime.playerHeroes;
export const playerResources: typeof Contract.playerResources = runtime.playerResources;
export const playerResourcesOrZero: typeof Contract.playerResourcesOrZero = runtime.playerResourcesOrZero;
/** Shared game context with a stable scale-1 fallback before hydration. No scope required. */
export const gameContext: typeof Contract.gameContext = runtime.gameContext;
export const inventorySlotIdentity: typeof Contract.inventorySlotIdentity = runtime.inventorySlotIdentity;
export const upgradeIdentity: typeof Contract.upgradeIdentity = runtime.upgradeIdentity;
export const currentUpgrades: typeof Contract.currentUpgrades = runtime.currentUpgrades;
export const battleTagName: typeof Contract.battleTagName = runtime.battleTagName;
