// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './standard-game.runtime.js';
import type * as Contract from './standard-game-contracts.js';

export type * from './standard-game-contracts.js';

export const races: typeof Contract.races = runtime.races;
export const playerColors: typeof Contract.playerColors = runtime.playerColors;
export const weaponOrArmorUpgradeRawcodes: typeof Contract.weaponOrArmorUpgradeRawcodes = runtime.weaponOrArmorUpgradeRawcodes;
export const meleeModes: typeof Contract.meleeModes = runtime.meleeModes;
export const raceInfo: typeof Contract.raceInfo = runtime.raceInfo;
export const normalizeMode: typeof Contract.normalizeMode = runtime.normalizeMode;
export const isMode: typeof Contract.isMode = runtime.isMode;
export const modeInfo: typeof Contract.modeInfo = runtime.modeInfo;
export const playerColor: typeof Contract.playerColor = runtime.playerColor;
export const normalizeUpgradeRawcode: typeof Contract.normalizeUpgradeRawcode = runtime.normalizeUpgradeRawcode;
export const isWeaponOrArmorUpgrade: typeof Contract.isWeaponOrArmorUpgrade = runtime.isWeaponOrArmorUpgrade;
/** Select an exact record. No fallback across modes, races, seasons or teams. */
export const statsForMode: typeof Contract.statsForMode = runtime.statsForMode;
export const formatGameTime: typeof Contract.formatGameTime = runtime.formatGameTime;
export const dayNightState: typeof Contract.dayNightState = runtime.dayNightState;
export const heroExperienceState: typeof Contract.heroExperienceState = runtime.heroExperienceState;
export const valuePoolRatio: typeof Contract.valuePoolRatio = runtime.valuePoolRatio;
export const isValuePoolDepleted: typeof Contract.isValuePoolDepleted = runtime.isValuePoolDepleted;
export const upkeepState: typeof Contract.upkeepState = runtime.upkeepState;
export const orderHeadToHeadPlayers: typeof Contract.orderHeadToHeadPlayers = runtime.orderHeadToHeadPlayers;
export const orderMatchTeams: typeof Contract.orderMatchTeams = runtime.orderMatchTeams;
export const presentationPlayerColor: typeof Contract.presentationPlayerColor = runtime.presentationPlayerColor;
export const formatHeroLevelProgress: typeof Contract.formatHeroLevelProgress = runtime.formatHeroLevelProgress;
