// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './store.runtime.js';
import type * as Contract from './store-contracts.js';

export type * from './store-contracts.js';

export const createSelectorStore: typeof Contract.createSelectorStore = runtime.createSelectorStore;
/**
 * Memoize selector calls by first-argument object identity and Object.is option arguments.
 * The object key is held weakly and up to 16 option variants are retained per identity.
 * The caller owns invalidation: inputs and returned values must be treated as immutable.
 */
export const createMemoizedSelector: typeof Contract.createMemoizedSelector = runtime.createMemoizedSelector;
/** Adapt an immediate store to the dependency-free TC39/RxJS observer contract. */
export const createSubscribable: typeof Contract.createSubscribable = runtime.createSubscribable;
