// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './analytics.runtime.js';
/** Optional framework-neutral current-match history. No timers, transport or persistence. */
export const createMatchHistory = runtime.createMatchHistory;
