// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './assets.runtime.js';
export const assetBaseUrl = runtime.assetBaseUrl;
export const countryFlagCatalogVersion = runtime.countryFlagCatalogVersion;
export const resolveAssetBaseUrl = runtime.resolveAssetBaseUrl;
export const normalizeAssetBaseUrl = runtime.normalizeAssetBaseUrl;
export const countryFlagFileName = runtime.countryFlagFileName;
export const countryFlagUrl = runtime.countryFlagUrl;
export const countryFlagManifestUrl = runtime.countryFlagManifestUrl;
export const bnetLeagueCatalogVersion = runtime.bnetLeagueCatalogVersion;
/** Unknown/missing division IDs return undefined. Does not infer division from MMR. */
export const bnetLeagueIconUrl = runtime.bnetLeagueIconUrl;
export const bnetLeagueManifestUrl = runtime.bnetLeagueManifestUrl;
