// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './game-data.runtime.js';
/** Loads only the exact revision advertised by the recorder; never substitutes the latest build. */
export const loadGameData = runtime.loadGameData;
/** A standard-game estimate derived from this revision's ability configuration and observed game time. */
export const abilityCooldown = runtime.abilityCooldown;
export const abilityCooldownsForState = runtime.abilityCooldownsForState;
