// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './index.runtime.js';
export { SDK_VERSION, PROTOCOL_VERSION, SUPPORTED_PROTOCOL_VERSIONS } from './version.js';
/** Runtime error constructors exposed for `instanceof` and explicit error creation. */
export const PermissionRequiredError = runtime.PermissionRequiredError;
export const ConnectionError = runtime.ConnectionError;
export const ProtocolError = runtime.ProtocolError;
export const HostActionError = runtime.HostActionError;
/** Runtime class identity for `instanceof`; clients are created through the factory functions. */
export const W3BoosterClient = runtime.W3BoosterClient;
/** Open a W3Booster transport without waiting for hydrated state. */
export const openClient = runtime.openClient;
/** @deprecated Use openClient() for transport-only startup or startClient() for synchronized state. */
export const connect = runtime.connect;
/** Create a client and wait for the frontend lifecycle milestone requested by startup options. */
export const startClient = runtime.startClient;
/** Create a client synchronously so lifecycle listeners can be attached before connecting. */
export const createClient = runtime.createClient;
export const isAbortError = runtime.isAbortError;
export const isW3BoosterError = runtime.isW3BoosterError;
export const classifyW3BoosterError = runtime.classifyW3BoosterError;
export const canUseHostCapability = runtime.canUseHostCapability;
export const UNAVAILABLE_HOST_SNAPSHOT = runtime.UNAVAILABLE_HOST_SNAPSHOT;
