// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './selectors.runtime.js';
export const isActiveMatch = runtime.isActiveMatch;
export const isObserverOrReplayMatch = runtime.isObserverOrReplayMatch;
export const hasCapability = runtime.hasCapability;
export const broadcasterPlayer = runtime.broadcasterPlayer;
export const headToHeadPair = runtime.headToHeadPair;
export const groupPlayersByTeam = runtime.groupPlayersByTeam;
export const broadcasterFirstTeams = runtime.broadcasterFirstTeams;
export const playerRelationship = runtime.playerRelationship;
export const playerDisplayIdentity = runtime.playerDisplayIdentity;
export const heroInventory = runtime.heroInventory;
export const playerHeroes = runtime.playerHeroes;
export const playerResources = runtime.playerResources;
export const playerResourcesOrZero = runtime.playerResourcesOrZero;
/** Shared game context with a stable scale-1 fallback before hydration. No scope required. */
export const gameContext = runtime.gameContext;
export const inventorySlotIdentity = runtime.inventorySlotIdentity;
export const upgradeIdentity = runtime.upgradeIdentity;
export const currentUpgrades = runtime.currentUpgrades;
export const battleTagName = runtime.battleTagName;
