import type * as Contract from './selectors-contracts.js';
export type * from './selectors-contracts.js';
export declare const isActiveMatch: typeof Contract.isActiveMatch;
export declare const isObserverOrReplayMatch: typeof Contract.isObserverOrReplayMatch;
export declare const hasCapability: typeof Contract.hasCapability;
export declare const broadcasterPlayer: typeof Contract.broadcasterPlayer;
export declare const headToHeadPair: typeof Contract.headToHeadPair;
export declare const groupPlayersByTeam: typeof Contract.groupPlayersByTeam;
export declare const broadcasterFirstTeams: typeof Contract.broadcasterFirstTeams;
export declare const playerRelationship: typeof Contract.playerRelationship;
export declare const playerDisplayIdentity: typeof Contract.playerDisplayIdentity;
export declare const heroInventory: typeof Contract.heroInventory;
export declare const playerHeroes: typeof Contract.playerHeroes;
export declare const playerResources: typeof Contract.playerResources;
export declare const playerResourcesOrZero: typeof Contract.playerResourcesOrZero;
/** Shared game context with a stable scale-1 fallback before hydration. No scope required. */
export declare const gameContext: typeof Contract.gameContext;
export declare const inventorySlotIdentity: typeof Contract.inventorySlotIdentity;
export declare const upgradeIdentity: typeof Contract.upgradeIdentity;
export declare const currentUpgrades: typeof Contract.currentUpgrades;
export declare const battleTagName: typeof Contract.battleTagName;
