import type * as Contract from './standard-game-contracts.js';
export type * from './standard-game-contracts.js';
export declare const races: typeof Contract.races;
export declare const playerColors: typeof Contract.playerColors;
export declare const weaponOrArmorUpgradeRawcodes: typeof Contract.weaponOrArmorUpgradeRawcodes;
export declare const meleeModes: typeof Contract.meleeModes;
export declare const raceInfo: typeof Contract.raceInfo;
export declare const normalizeMode: typeof Contract.normalizeMode;
export declare const isMode: typeof Contract.isMode;
export declare const modeInfo: typeof Contract.modeInfo;
export declare const playerColor: typeof Contract.playerColor;
export declare const normalizeUpgradeRawcode: typeof Contract.normalizeUpgradeRawcode;
export declare const isWeaponOrArmorUpgrade: typeof Contract.isWeaponOrArmorUpgrade;
export declare const statsForMode: typeof Contract.statsForMode;
export declare const preferredStats: typeof Contract.preferredStats;
export declare const formatGameTime: typeof Contract.formatGameTime;
export declare const dayNightState: typeof Contract.dayNightState;
export declare const heroExperienceState: typeof Contract.heroExperienceState;
export declare const valuePoolRatio: typeof Contract.valuePoolRatio;
export declare const isValuePoolDepleted: typeof Contract.isValuePoolDepleted;
export declare const upkeepState: typeof Contract.upkeepState;
export declare const orderHeadToHeadPlayers: typeof Contract.orderHeadToHeadPlayers;
export declare const orderMatchTeams: typeof Contract.orderMatchTeams;
export declare const presentationPlayerColor: typeof Contract.presentationPlayerColor;
export declare const formatHeroLevelProgress: typeof Contract.formatHeroLevelProgress;
