// Generated from the public contract by scripts/generate-api-facades.mjs.
// Do not edit this file directly.
// @ts-expect-error The runtime intentionally has no hand-maintained declaration file.
import * as runtime from './standard-game.runtime.js';
export const races = runtime.races;
export const playerColors = runtime.playerColors;
export const weaponOrArmorUpgradeRawcodes = runtime.weaponOrArmorUpgradeRawcodes;
export const meleeModes = runtime.meleeModes;
export const raceInfo = runtime.raceInfo;
export const normalizeMode = runtime.normalizeMode;
export const isMode = runtime.isMode;
export const modeInfo = runtime.modeInfo;
export const playerColor = runtime.playerColor;
export const normalizeUpgradeRawcode = runtime.normalizeUpgradeRawcode;
export const isWeaponOrArmorUpgrade = runtime.isWeaponOrArmorUpgrade;
export const statsForMode = runtime.statsForMode;
export const preferredStats = runtime.preferredStats;
export const formatGameTime = runtime.formatGameTime;
export const dayNightState = runtime.dayNightState;
export const heroExperienceState = runtime.heroExperienceState;
export const valuePoolRatio = runtime.valuePoolRatio;
export const isValuePoolDepleted = runtime.isValuePoolDepleted;
export const upkeepState = runtime.upkeepState;
export const orderHeadToHeadPlayers = runtime.orderHeadToHeadPlayers;
export const orderMatchTeams = runtime.orderMatchTeams;
export const presentationPlayerColor = runtime.presentationPlayerColor;
export const formatHeroLevelProgress = runtime.formatHeroLevelProgress;
